class CaeRules:
    KEYWORDS = [
        "var",
        "public",
        "private",
        "class",
        "static",
        "int",
        "void",
        "str",
        "method",
        "func",
        "char",
        "object",
        "any",
        "if",
        "elif",
        "else",
        "for",
        "while",
        "iter",
        "until",
        "enum",
        "import",
        "bool",
        "true",
        "undefined",
        "none",
        "null",
        "false",
        "instance"
    ]

    INDENT_SIZES = [
        2,
        4, 
        8
    ]

    DEFAULT_PROGRAM_TOKENS = [
        {'NEWLINE': '\n\n'},
        {'KEYWORD': 'public'},
        {'WHITESPACE': ' '},
        {'KEYWORD': 'class'},
        {'WHITESPACE': ' '},
        {'IDENTIFIER': 'Hello'},
        {'WHITESPACE': ' '},
        {'LBRACE': '{'},
        {'NEWLINE': '\n\n'},
        {'INDENT': '    '},
        {'KEYWORD': 'public'},
        {'WHITESPACE': ' '},
        {'KEYWORD': 'void'},
        {'WHITESPACE': ' '},
        {'KEYWORD': 'method'},
        {'WHITESPACE': ' '},
        {'IDENTIFIER': 'main'},
        {'LPAREN': '('},
        {'RPAREN': ')'},
        {'WHITESPACE': ' '},
        {'LBRACE': '{'},
        {'NEWLINE': '\n\n'},
        {'INDENT': '  '},
        {'IDENTIFIER': 'console'},
        {'DOT': '.'},
        {'IDENTIFIER': 'stdout'},
        {'LPAREN': '('},
        {'STRING': 'Hello World!'},
        {'RPAREN': ')'},
        {'SEMI': ';'},
        {'NEWLINE': '\n\n'},
        {'INDENT': '    '},
        {'RBRACE': '}'},
        {'NEWLINE': '\n\n'},
        {'RBRACE': '}'}
    ]